set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR arm)

set(PREFIX arm-fzm_k2-linux-gnueabihf-)
set(PLATFORM /build/ltesdkroot/Platforms/LINUX/FB_FZM_PS_LFS_REL_2019_05_28/os/archs/arm-fzm_k2-linux-gnueabihf)
set(BLD_TOOLS ${PLATFORM}/bld-tools/x86_64-pc-linux-gnu)

set(CMAKE_SYSROOT ${PLATFORM}/sys-root)

set(CMAKE_C_COMPILER ${BLD_TOOLS}/bin/${PREFIX}gcc)
set(CMAKE_CXX_COMPILER ${BLD_TOOLS}/bin/${PREFIX}g++)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
